sonar.projectKey=pos-fiap-billing-service
sonar.projectName=pos-fiap-billing-service
sonar.sources=app
sonar.tests=tests
sonar.test.inclusions=tests/**/*.py
sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml
