apiVersion: v1
kind: Secret
metadata:
  name: billing-service-secrets
type: Opaque
stringData:
  DATABASE_URL: postgresql+psycopg://user:password@host:5432/billing_service
  RABBITMQ_URL: amqp://workshop:password@rabbitmq.workshop.svc.cluster.local:5672/workshop
  CATALOG_BACKEND: dynamodb
  AWS_REGION: us-east-1
  DYNAMODB_TABLE_NAME: billing_catalog
  DYNAMODB_ENDPOINT_URL: ""
